---
title: "Manuscript Figures"
author: "Valerie Jill Sydnor"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
library(readr)
library(tidyr)
library(ggplot2)
library(Hmisc)
library(plyr)
library(RColorBrewer)
library(reshape2)
library(PupillometryR)
library(ggcorrplot)
```

```{r}
df.ZAP <- read.csv("../statistics/Sydnor2022_ZAPR01_Amygdala_TMSfMRIdMRI.csv")
```

**FIGURE 2: Amygdala BOLD Signal Change Following TMS Administered to vlPFC Connectivity Peaks**

Figure 2B

```{r}
datal <- melt(df.ZAP, id.vars = c("Case"), measure.vars = c("left_amygdala.vlPFCTMS"), variable.name = "Region", value.name = "ER")
datal$sign <- as.factor(df.ZAP$left_amygdala_sign.vlPFCTMS)

jpeg("../../Figures/Images/LeftAmygdala_RawEvokedResponseMagnitude_RainCloudPlot.jpg", units="in", width=7.3, height=7, res=800)

ggplot(data = datal, aes(y = ER, x = Region, fill = Region)) +
geom_flat_violin(position = position_nudge(x = .12, y = 0), alpha = .99, fill = c("#3f55a5")) +
geom_point(aes(y=ER, x=.8), pch = 21, position = position_jitter(width = .2), size = 4, stroke = .5, alpha = .85) +
geom_boxplot(width = .13, position = position_nudge(x = -.23), outlier.shape = NA, alpha = 0.5, fill = c("#3f55a5")) +
scale_color_manual(values=c("black","black")) +
scale_fill_manual(values=c("black","gray65")) +
expand_limits(x = 3.5) +
theme_bw() +
theme(
text = element_text(size = 10),
axis.title.x = element_blank(),
axis.title.y = element_blank(),
axis.text.x = element_blank(),
axis.text.y = element_text(family="Arial",size=28, color = "black"),
axis.ticks.x = element_blank(),
legend.position = "none",
panel.border = element_blank(),
panel.grid.minor = element_blank(),
panel.grid.major = element_blank(),
axis.line.x = element_line(colour = 'black', size=.8, linetype='solid'),
axis.line.y = element_line(colour = 'black', size=.8, linetype='solid')) +
scale_y_continuous(breaks = c(-0.6,-0.3,0,0.3,0.6), limits = c(-0.58,0.61)) 
```


Figure 2C

```{r, warning=F}
ERdata <- df.ZAP[,c(10,11,12,13,14,16)] 
ERdata.diff <- as.data.frame(lapply(ERdata, function(x){(abs(df.ZAP$left_amygdala.vlPFCTMS) - abs(x))}))
ERdata.diff$Case <- df.ZAP$Case

datal <- melt(ERdata.diff, id.vars = c("Case"), measure.vars = c("left_pallidum.vlPFCTMS", "left_caudate.vlPFCTMS",  "left_putamen.vlPFCTMS","left_hippocampus.vlPFCTMS","left_thalamus.vlPFCTMS","left_accumbens.vlPFCTMS"), variable.name = "Region", value.name = "ERdiff")

fills <- c("#293d8a","#3f55a5","#7689cc","#88a2d1","#9ab5e3","#b4c9ed")

jpeg("../../Figures/Images/EvokedResponseMagnitude_Difference_BoxPlots.jpg", units="in", width=8.2, height=5.6, res=800)

ggplot(data = datal, aes(y = ERdiff, x = Region, fill = Region)) +
geom_point(aes(y = ERdiff, color = Region), position = position_jitter(width = .3), size = 1.7, alpha = 0.9) +
geom_boxplot(width = .25, outlier.shape = NA, alpha = 0.5, notch=T) +
scale_color_manual(values=fills) +
scale_fill_manual(values=fills) +
scale_x_discrete(expand = c(0.1,0)) +
theme_bw() +
theme(
axis.title.x = element_blank(),
axis.title.y = element_blank(),
axis.text.x = element_blank(),
axis.text.y = element_text(family="Arial",size=22, color = "black"),
legend.position = "none",
panel.border = element_blank(),
panel.grid.minor = element_blank(),
panel.grid.major = element_blank(),
axis.line.x = element_line(colour = 'black', size=0.75, linetype='solid'),
axis.line.y = element_line(colour = 'black', size=0.75, linetype='solid'),
) +
scale_y_continuous(limits = c(-.725,.55), breaks = c(-.6,-.4,-.2,.2,.4,.6)) +
geom_hline(yintercept=0, size = 0.5)
```

**FIGURE S1: TMS Evoked Responses Within Amygdala Subdivisions**

Figure S1A

```{r}
Juleich.long <- melt(df.ZAP, id.vars = c("Case"), measure.vars = c("left_basolateral_amygdala.vlPFCTMS", "left_superficial_amygdala.vlPFCTMS", "left_centromedial_amygdala.vlPFCTMS" ), variable.name = "Division", value.name = "ER")

jpeg("../../Figures/Images/LeftAmygdala_Subdivisions_EvokedResponse.jpg", units="in", width=7.6, height=6.5, res=800)

ggplot(data = Juleich.long, aes(y = ER, x = Division)) +
geom_point(aes(y = ER), fill = "#3f55a5", color = "white", pch = 21, position = position_jitter(width = .25), size = 4.5, stroke = .5, alpha = .85) +
geom_boxplot(width = .18, position = position_nudge(x = 0), outlier.shape = NA, alpha = 0.6, lwd = 1) +
theme_bw() +
theme(
text = element_text(size = 10),
axis.title.x = element_blank(),
axis.title.y = element_blank(),
axis.text.y = element_text(family="Arial",size=28, color = "black"),
legend.position = "none",
panel.border = element_blank(),
panel.grid.minor = element_blank(),
panel.grid.major = element_blank(),
axis.line.x = element_line(colour = 'black', size=.6, linetype='solid'),
axis.line.y = element_line(colour = 'black', size=.6, linetype='solid')) +
scale_x_discrete(labels = c("\nBasolateral","\nSuperficial","\nCentromedial")) +
scale_y_continuous(limits = c(-.81,.8), breaks = c(-.6,-.3,0,.3,.6)) +
geom_hline(yintercept=0, size = 0.5)
```

Figure S1B

```{r}
divisions <- df.ZAP %>% dplyr::select(left_superficial_amygdala.vlPFCTMS, left_centromedial_amygdala.vlPFCTMS,  left_basolateral_amygdala.vlPFCTMS)
ER.corr <- cor(divisions, method = c("pearson"))
colnames(ER.corr) <- c("Superficial", "Centromedial", "Basolateral")
rownames(ER.corr) <- c("Superficial", "Centromedial", "Basolateral")

jpeg("../../Figures/Images/LeftAmygdala_Subdivisions_CorrelationMatrix.jpg", units="in", width=6.5, height=6.5, res=800)

ggcorrplot(ER.corr, method = "square", type = "upper", show.legend = FALSE, show.diag = FALSE, lab = TRUE, lab_size = 8, lab_col = "black", colors = c("#9ab5e3", "white", "#324280"), outline.color=c("white"),  ggtheme = theme_classic())
```

**FIGURE 4: vlPFC-Amygdala White Matter Pathway Fiber Density Impacts Subcortical TMS Evoked Responses**

Figure 4A

```{r}
FD_agecorrected <- lm(df.ZAP$FD_mean_5 ~ df.ZAP$age)
plotdata <- data.frame(FD_agecorrected$residuals, df.ZAP$left_amygdala.vlPFCTMS, df.ZAP$left_amygdala_sign.vlPFCTMS)
plotdata$df.ZAP.left_amygdala_sign.vlPFCTMS <- as.factor(plotdata$df.ZAP.left_amygdala_sign.vlPFCTMS)

jpeg("../../Figures/Images/EvokedResponseMagnitudeColored_PathwayFD_AgeCorrected_Scatterplot.jpg", units="in", width=7.3, height=6.6, res=800)

ggplot(plotdata, aes(y=abs(df.ZAP.left_amygdala.vlPFCTMS), x=FD_agecorrected.residuals, )) +
geom_point(aes(y=abs(df.ZAP.left_amygdala.vlPFCTMS), x=FD_agecorrected.residuals, color = df.ZAP.left_amygdala_sign.vlPFCTMS, fill = df.ZAP.left_amygdala_sign.vlPFCTMS), shape=21, size=4.5) +
scale_color_manual(values=c("white","white")) +
scale_fill_manual(values=c("#66467d","#cab2db")) +
labs(y="\nLeft Amygdala Evoked Response Magnitude\n", x="\nPathway Fiber Density\n") +
geom_smooth(method='lm', se=TRUE, fill=alpha(c("gray70"),.7), col="black") +
theme(
axis.title.x=element_blank(),
axis.title.y=element_blank(),
legend.position = "none",
axis.line = element_line(color = "black"),
axis.text=element_text(family="Arial",size=32, color = "black"),
panel.background=element_blank()) +
scale_y_continuous(limits = c(0,0.65)) +
scale_x_continuous(limits = c(-0.06,0.08), breaks = c(-0.05, 0, 0.05))
```

Figure 4B

```{r}
jpeg("../../Figures/Images/SignedEvokedResponse_PathwayFD_AgeCorrected_Scatterplot.jpg", units="in", width=7.3, height=6.6, res=800)

ggplot(plotdata, aes(y=df.ZAP.left_amygdala.vlPFCTMS, x=FD_agecorrected.residuals, group=df.ZAP.left_amygdala_sign.vlPFCTMS)) +
geom_point(aes(y=df.ZAP.left_amygdala.vlPFCTMS, x=FD_agecorrected.residuals, color = df.ZAP.left_amygdala_sign.vlPFCTMS, fill = df.ZAP.left_amygdala_sign.vlPFCTMS), shape=21, size=4.5) +
scale_color_manual(values=c("#66467d","#cab2db")) +
scale_fill_manual(values=c("#66467d","#cab2db")) +
labs(y="\nLeft Amygdala Evoked Response Magnitude\n", x="\nPathway Fiber Density\n") +
geom_smooth(method='lm', se=FALSE, size=2,  fullrange = T, aes(color=df.ZAP.left_amygdala_sign.vlPFCTMS)) +
theme(
axis.title.x=element_blank(),
axis.title.y=element_blank(),
legend.position = "none",
axis.line = element_line(color = "black"),
axis.text=element_text(family="Arial",size=32, color = "black"),
panel.background=element_blank()) +
scale_y_continuous(limits = c(-0.62,0.65), breaks = c(-0.6,-0.3,0,0.3,0.6)) +
scale_x_continuous(limits = c(-0.06,0.08), breaks = c(-0.05, 0, 0.05))
```
Figure 4D

```{r}
ER.FD.partialR <- data.frame(Region=character(), rho=double())
ER.FD.partialR <- ER.FD.partialR %>% add_row(Region= "Amyg.vlPFC", rho= 0.360)
ER.FD.partialR <- ER.FD.partialR %>% add_row(Region= "Amyg.control", rho= 0.0873)

jpeg("../../Figures/Images/AmygdalaEvokedResponse_PathwayFD_vlPFCvControl_RhoPlot.jpg", units="in", width=4, height=6.6, res=800)

plot_order <- c('Amyg.vlPFC','Amyg.control')

ggplot(data=ER.FD.partialR, aes(x=(factor(Region, level = plot_order)), y=rho, fill=Region)) + geom_col() + 
labs(x="TMS Stimulation Site") +
labs(y="\nSpearman's Rho\n") +
theme_minimal()+
theme(
axis.title.x=element_blank(),
axis.title.y=element_blank(),
axis.line = element_line(colour = "black"),
axis.text.y = element_text(family="Arial",size=32, color = "black"),
axis.text.x = element_blank(),
panel.grid.major.y = element_blank(),
panel.grid.major.x = element_blank(),
panel.grid.minor.y = element_blank(),
axis.ticks = element_line(),
legend.position = "none") +
scale_fill_manual(values=c("#03540e","#85629f"))
```